### ISSUE TITLE
The proper fix here in my opinion would be that the [faraday-net_http gem](https://github.com/lostisland/faraday-net_http) would declare the `net-http` gem as a dependency.

### ISSUE THREAD

**Issue by nicho1991** [ruby/net-imap#117]
The proper fix here in my opinion would be that the [faraday-net_http gem](https://github.com/lostisland/faraday-net_http) would declare the `net-http` gem as a dependency.

This is the explanation of what's happening:

* When the `faraday-net_http` gem is required, it then requires `net/http`.
* Then the stdlib version of `net/http` is loaded, since bundler doesn't know `net-http` is a gem dependency, so it doesn't add the gemified version to to the `$LOAD_PATH`.
* Then the stdlib version of `net/http` requires `net/protocol` relatively, since that's what it used to happen before these gems were gemified. See https://github.com/ruby/net-http/commit/6da598e928f0cc817b1d17209dfaf7fed4c9dff7. So the stdlib version of `net/protocol` is loaded.
* Then when `net-imap` is required, it also uses `net-protocol` but this time the gemified version of `net-protocol` is used, because `net-imap` properly declares it as a dependency, so `bundler` knows about it and has put it in the `$LOAD_PATH`. This is what causes the double load of `net/protocol`.

If `faraday-net_http` explicitly declares `net-http` as a dependency, then the gemified version of all gems involved will be consistently loaded and there will be no redefinition warnings.

I suggest that you proposed this update to `faraday-net_http` and in the mean time, you can workaround this issue by adding `gem "net-http"` to your `Gemfile`.

_Originally posted by @deivid-rodriguez in https://github.com/ruby/net-imap/issues/16#issuecomment-803086765_

**Comment by nevans** [comment]
Was this issue created for SEO?  🙂  For anyone coming here from a search engine, please see the context here:
* #16

**Comment by nicho1991** [comment]
> Was this issue created for SEO?  🙂  For anyone coming here from a search engine, please see the context here:
> * #16

It was just me mistakenly creating it when I tried to copy it to my local repo for reference. My apologies
