### ISSUE TITLE
0.3.5 lib/net/imap/flags.rb file permissions regression

### ISSUE THREAD

**Issue by aaronjensen** [ruby/net-imap#154]
For some reason, permissions of `lib/net/imap/flags.rb` has 600 file permissions, rather than 664, which caused a deployment issue for us.

```
/.../ruby/3.2.0/gems/net-imap-0.3.5/lib/net/imap.rb:2389:in `require_relative': cannot load such file -- /.../ruby/3.2.0/gems/net-imap-0.3.5/lib/net/imap/flags (LoadError)
from /.../ruby/3.2.0/gems/net-imap-0.3.5/lib/net/imap.rb:2389:in `<top (required)>'
```

![CleanShot 2023-06-12 at 14 46 15@2x](https://github.com/ruby/net-imap/assets/8588/7fb18da1-eb0e-40df-bcc1-a13c73883a40)

**Comment by nevans** [comment]
Yikes.  Sorry about that!  I'll try to get 0.3.6 out shortly, to fix that.

**Comment by nevans** [comment]
@aaronjensen 0.3.6 should have all files as 664 and all directories as 775.

**Comment by aaronjensen** [comment]
Thank you for the quick turnaround!
