### ISSUE TITLE
Parsing error when BYE response has no text following the word BYE

### ISSUE THREAD

**Issue by danarnold** [ruby/net-imap#229]
When receiving a response from an IMAP server containing the text `* BYE \r\n`, Net::IMAP 0.4.5 throws a Net::IMAP::ResponseParseError. For example, with debug enabled, here is this happening (iCloud servers send this response):

```
C: RUBY0004 LOGOUT
S: * BYE
Net::IMAP::ResponseParser parse_error: unexpected "\r" (expected " ")
  tokenized : "* BYE"
  remaining : "\r\n"
  @lex_state: EXPR_BEG
  @pos      : 5
  @token    : nil
  caller[ 0]: SP!                            (parser_utils:54)
  caller[ 1]: resp_cond_bye                  (response_parser:806)
  caller[ 2]: response_data                  (response_parser:726)
  caller[ 3]: response                       (response_parser:656)
  caller[ 4]: parse                          (response_parser:33)
  caller[ 5]: get_response                   (imap:2603)
  caller[ 6]: receive_responses              (imap:2498)
  caller[ 7]: start_receiver_thread          (imap:2475)
Net::IMAP::ResponseParseError: unexpected "\r" (expected " ")
from /home/dan/.gem/ruby/3.2.2/gems/net-imap-0.4.5/lib/net/imap/response_parser/parser_utils.rb:234:in `parse_error'
```

Here's an example showing it works when BYE is followed with text:

```
C: RUBY0003 LOGOUT
S: * BYE IMAP4rev1 Server logging out
S: RUBY0003 OK LOGOUT completed
#<#<Class:0x00007fc8d59c96b8>:Net::IMAP::TaggedResponse:0x001653c8
   data = #<#<Class:0x00007fc8d59c9438>:Net::IMAP::ResponseText:0x001653f0
      code = nil,
      text = "LOGOUT completed"
   >,
   name = "OK",
   raw_data = "RUBY0003 OK LOGOUT completed\r\n",
   tag = "RUBY0003"
>
```

As far as I can tell from reading RFC9501, it's valid for BYE responses not to have any text following the word BYE. Quoting from the syntax specified in "9. Formal Syntax":

```
response        = *(continue-req / response-data) response-done

response-data   = "*" SP (resp-cond-state / resp-cond-bye /
                  mailbox-data / message-data / capability-data /
                  enable-data) CRLF
```
```
resp-cond-bye   = "BYE" SP resp-text
```
```
resp-text       = ["[" resp-text-code "]" SP] [text]
```
```
text            = 1*(TEXT-CHAR / UTF8-2 / UTF8-3 / UTF8-4)
                    ; Non-ASCII text can only be returned
                    ; after ENABLE IMAP4rev2 command

TEXT-CHAR       = <any CHAR except CR and LF>
```

The relevant thing to note is that `resp-text` lists `text` as optional by enclosing it in square brackets.

**Comment by nevans** [comment]
Thanks for the report.

So... while `text` _is_ optional, the space (`SP`) between "BYE" and `resp-text` is technically required!
```
irb(main):009:0> p.parse "* bye \r\n"
=>
#<struct Net::IMAP::UntaggedResponse
 name="BYE",
 data=#<struct Net::IMAP::ResponseText code=nil, text="">,
 raw_data="* bye \r\n">
irb(main):012:0> p.parse "* bye\r\n" rescue $!
=> #<Net::IMAP::ResponseParseError: unexpected "\r" (expected " ")
```

But I think that the _spirit_ of RFC9051 should make the `SP` optional as well.  And I know that at least one (very popular) email provider _does_ leave the space out though, and I have been meaning to make it optional in our parser.  In fact, I even reported an errata about this, back in February: https://www.rfc-editor.org/errata/eid7343

Unfortunately I never got around to merging my code that handles it this way!  I'll look into cleaning up that code, adding a couple of tests, and merging it (tomorrow?). 🙂

**Comment by danarnold** [comment]
Ah, you're right of course. I didn't realize that the space was missing in the response. My mistake.

I agree that the RFC should change; it seems silly to require a space before `\r\n`, especially when there are existing major service providers that respond without one.

It's great to hear that you intend to update the parser to support handling no space, and that it might get implemented so quickly. Thank you! I'll close this issue, since it's not actually a bug.

**Comment by nevans** [comment]
It may not be a "bug" per the RFC, but implementing the workaround is still a useful enough issue to keep track of.   Especially if I don't get to it quickly (I'm traveling today), it'll be nice to have an open reminder that someone else is interested in it. 🙂

**Comment by danarnold** [comment]
Sure, sounds good. 👍
