### ISSUE TITLE
Frozen SearchResult breaks IMAP.find with what: :last option

### ISSUE THREAD

**Issue by stanley90** [ruby/net-imap#262]
PR #236 introduced the `SearchResult` class, which is actually a [frozen Array](https://github.com/ruby/net-imap/blob/153e69f973af818f902987b1c50a9401975eef7c/lib/net/imap/search_result.rb#L32).
However, this breaks the `what: :last` option in the `mail` gem [here](https://github.com/mikel/mail/blob/3dd53e046024f36cb6bfec57a6a131c45e0121fa/lib/mail/network/retriever_methods/imap.rb#L79)
`FrozenError: can't modify frozen Net::IMAP::SearchResult`

**Comment by nevans** [comment]
Thanks for reporting this.  I should have realized that freezing by default wouldn't be backward compatible!  That's fixed by #263.

I'm hoping that using the subclass is still okay though.  I'd prefer not to add a config option (e.g: `search_result_type => Array | SearchResult | ESearchResult`) and I'd prefer to return the same type regardless of whether or not we see a `MODSEQ`.  What do you think?

**Comment by stanley90** [comment]
Honestly, I'm not convinced that the `mail` gem should just `reverse!` it in place, safer would be to make a copy.
Otherwise I guess an Array subclass is okay.
Btw, can I expect a release rather soon? Need to decide whether to temporarily work around this / downgrade 🙂

**Comment by nevans** [comment]
> Honestly, I'm not convinced that the `mail` gem should just `reverse!` it in place, safer would be to make a copy.  Otherwise I guess an Array subclass is okay. 

I would prefer that too.  But backward compatibility is more important, especially since there were no deprecation warnings.

> Btw, can I expect a release rather soon? Need to decide whether to temporarily work around this / downgrade 🙂

Yes, today or tomorrow.  🙂

**Comment by nevans** [comment]
@stanley90 It's been released.  Let me know if v0.4.10 works for you.

**Comment by stanley90** [comment]
> @stanley90 It's been [released](https://github.com/ruby/net-imap/releases/tag/v0.4.10). Let me know if `v0.4.10` works for you.

Works, thanks!
