### ISSUE TITLE
Wrong response after uid_move?

### ISSUE THREAD

**Issue by stanley90** [ruby/net-imap#285]
Hi, I'm replacing the legacy "copy + delete" solution with `uid_move`, but I need to know the new `uid` (which worked in the original solution). However, `uid_move` only returns an (untagged) response such as `RUBY0004 OK MOVE completed`.
After adding debug output to this gem, it seems that the correct response is returned from the IMAP server, but possibly not handled correctly in the gem (method name in square brackets):

```
[send_command] RUBY0004 UID MOVE #<Net::IMAP::MessageSet:0x000000010db627f0> destination_folder
[get_response] * OK [COPYUID 415 200 43]
[receive_responses] #<struct Net::IMAP::UntaggedResponse name="OK", data=#<struct Net::IMAP::ResponseText code=#<struct Net::IMAP::ResponseCode name="COPYUID", data=#<struct Net::IMAP::UIDPlusData uidvalidity=415, source_uids=[200], assigned_uids=[43]>>, text="">, raw_data="* OK [COPYUID 415 200 43]\r\n">
... # some EXPUNGE/EXISTS commands here
[get_response] RUBY0004 OK MOVE completed.
[receive_responses] #<struct Net::IMAP::TaggedResponse tag="RUBY0004", name="OK", data=#<struct Net::IMAP::ResponseText code=nil, text="MOVE completed.">, raw_data="RUBY0004 OK MOVE completed.\r\n">
[get_tagged_response] #<struct Net::IMAP::TaggedResponse tag="RUBY0004", name="OK", data=#<struct Net::IMAP::ResponseText code=nil, text="MOVE completed.">, raw_data="RUBY0004 OK MOVE completed.\r\n">
```
So it seems the data from `COPYUID` gets lost somewhere and it's not returned from `uid_move`.
Is this a bug or am I doing something wrong?
Thanks

**Comment by nevans** [comment]
The MOVE extension interacts with the UIDPLUS extension in a non-obvious way:
* [`UIDPLUS` specifies](https://www.rfc-editor.org/rfc/rfc4315#page-4) that the `COPYUID` response code is sent as part of the tagged response to the `COPY` or `UID COPY` command.
* [`MOVE` specifies](https://www.rfc-editor.org/rfc/rfc6851.html#section-4.3) that the `COPYUID` response code is sent _before_ the tagged response, in an untagged response.

That tagged response is `Net::IMAP`'s return value for `copy`, `move`, `uid_copy`, `uid_move`, and many other commands.  Some other `Net::IMAP` commands collect the relevant untagged responses and then throw away the tagged response.  I'd like to unify these two command result styles, but staying backwards compatible will be tricky.

However, unhandled untagged responses and unhandled response codes _with data_ are saved.  See:
* [Net::IMAP > Handling Server Responses](https://ruby.github.io/net-imap/Net/IMAP.html#class-Net::IMAP-label-Handling+server+responses)
* [Net::IMAP#responses](https://ruby.github.io/net-imap/Net/IMAP.html#method-i-responses)
* [Net::IMAP#clear_responses](https://ruby.github.io/net-imap/Net/IMAP.html#method-i-clear_responses)

You could also add a response handler, but that's really not needed here.

**Comment by nevans** [comment]
It would be good to document this difference between using `COPYUID` with `MOVE` and `COPY` in the rdoc.  An example would be especially nice.  Documentation PRs are welcome! 😉

**Comment by nevans** [comment]
Oh, and you might know this already, but you can get _most_ of your debug output with:
```ruby
Net::IMAP.debug = true
imap.add_response_handler do pp _1 end
```

(be aware that response handlers run in a different thread.)
