### ISSUE TITLE
Using PLAIN is broken in ruby 3.1.0

### ISSUE THREAD

**Issue by chdiza** [ruby/net-imap#52]
For years, up to and including ruby 2.7.5, I've been able to authenticate into some IMAP servers (even gmail) like so:
```
server = Net::IMAP.new(HOST, :port=>993, :ssl=>true)
server.authenticate('PLAIN', USERNAME, PASSWORD)
```
I've just upgraded to ruby 3.1.0 (from 2.7.5), and now this doesn't work on any of those servers.  Instead I get:
```
lib/ruby/gems/3.1.0/gems/net-imap-0.2.2/lib/net/imap.rb:1252:in `get_tagged_response': Authentication failed. (Net::IMAP::NoResponseError)
```

If I switch back to ruby 2.7.5 it works again.

I'm not knowledgeable enough to understand why this stopped working.

**Comment by chdiza** [comment]
The problem also occurs in ruby 3.0.3, so I did some more digging.  Bisection reveals that this is the commit that broke authenticating with PLAIN:
```
23f241b081d94b6385e24f550a24e65a66a0d46d is the first bad commit
commit 23f241b081d94b6385e24f550a24e65a66a0d46d
Author: nicholas a. evans <nicholas.evans@gmail.com>
Date:   Tue Apr 27 16:33:27 2021 -0400

    Move each authenticator to its own file
    
    Also updates rdoc with SASL specifications and deprecations.  Of these
    four, only `PLAIN` isn't deprecated!
    
    +@@authenticators+ was changed to a class instance var
    +@authenticators+.  No one should have been using the class variable
    directly, so that should be fine.
```

**Comment by chdiza** [comment]
Version 0.1.1 of the net-imap gem is fine.  But when I install a new ruby, `gem update` brings the buggy version of the gem into play.

**Comment by shugo** [comment]
@chdiza Thanks for your report. I've just released net-imap-0.2.3.  Please try it.

**Comment by chdiza** [comment]
Seems to work, thanks!!

**Comment by nevans** [comment]
Yikes. Sorry about that. 😳 Thanks, @shugo!
