### ISSUE TITLE
Promote @nevans to primary maitainer

### ISSUE THREAD

**Issue by hsbt** [ruby/net-imap#95]
@shugo It's time to add gem owner and admin of GitHub to @nevans. How about this?

**Comment by shugo** [comment]
:+1:

**Comment by hsbt** [comment]
@nevans I invite https://rubygems.org/profiles/nevans to https://rubygems.org/gems/net-imap.

**Comment by nevans** [comment]
@hsbt @shugo I'm honored! 🙏

I'll use my github access to configure https://ruby.github.io/net-imap with our rdoc.  🙂 

@hsbt, will you still handle gem releases?  If you'd like me to take some of that burden from you, I'll want to learn the procedures you've been using.  Regardless of who handles normal releases, it would be good for all owners have that ability, so urgent security issues or bugfixes can be addressed when one of us is unavailable or unresponsive.

**Comment by hsbt** [comment]
I and @shugo will release `net-imap` gem in the future. But you can release it with your convenience. We don't have release (or versioning) policy yet 😇 

If you have sone of concerns about release process, I and @shugo can advise it.

**Comment by shugo** [comment]
@nevans And you can merge pull requests without my review:)
